name: Publish package

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: git push origin --delete dist
      - run: git checkout --orphan dist
      - run: git rm --cached -r .
      - run: git config --global user.email "me@thiennguyen.dev"
      - run: git config --global user.name "Thien Nguyen"
      - run: git add -f asset lib package.json README.md
      - run: git commit -m "Publish"
      - run: git push origin dist

