name: Publish package

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build
      - run: git checkout --orphan dist
      - run: git config --global user.email "me@thiennguyen.dev"
      - run: git config --global user.name "Thien Nguyen"
      - run: git add -A -f asset lib package.json package-lock.json
      - run: git commit -m "Publish"
      - run: git push https://${GH_TOKEN}@github.com/thiennguyen93/hexo-component-inferno.git#dist

